GET http://localhost:3000/comments
Content-Type: application/json

###

GET http://localhost:3000/comments/3
Content-Type: application/json

###

POST http://localhost:3000/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjU2Njc4NTcwNX0.GOAhma8VrYcfFAECGqJG-Rv_wNSUOhdu-s6Mpj8RWSw

{
  "postId": 2,
  "userId": 2,
  "comment": "Ini ada komentar dari postId 2 dan userId 2"
}

###

DELETE http://localhost:3000/comments/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjU2Njc4NTcwNX0.GOAhma8VrYcfFAECGqJG-Rv_wNSUOhdu-s6Mpj8RWSw

###

PUT http://localhost:3000/comments/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjU2Njc4NTcwNX0.GOAhma8VrYcfFAECGqJG-Rv_wNSUOhdu-s6Mpj8RWSw

{
  "postId": 2,
  "userId": 2,
  "comment": "Ini adalah komentar yang sudah diedit dari postId 2 dan userId 2"
}