###
GET http://localhost:3000/signatures
Content-Type: application/json

###

GET http://localhost:3000/signatures/1
Content-Type: application/json

###

POST http://localhost:3000/signatures
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjU2Njc4NTcwNX0.GOAhma8VrYcfFAECGqJG-Rv_wNSUOhdu-s6Mpj8RWSw

{
  "petitionId": 3,
  "userId": 3
}

###

DELETE  http://localhost:3000/signatures/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjU2Njc4NTcwNX0.GOAhma8VrYcfFAECGqJG-Rv_wNSUOhdu-s6Mpj8RWSw