GET https://backend-final-project-eight.vercel.app/comments
Content-Type: application/json

###

GET https://backend-final-project-eight.vercel.app/comments/3
Content-Type: application/json

###

GET https://backend-final-project-eight.vercel.app/comments/3/posts
Content-Type: application/json

###

POST https://backend-final-project-eight.vercel.app/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjU2Njc4NTcwNX0.GOAhma8VrYcfFAECGqJG-Rv_wNSUOhdu-s6Mpj8RWSw

{
  "postId": 2,
  "userId": 2,
  "comment": "Ini ada komentar dari postId 2 dan userId 2"
}

###

DELETE https://backend-final-project-eight.vercel.app/comments/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjU2Njc4NTcwNX0.GOAhma8VrYcfFAECGqJG-Rv_wNSUOhdu-s6Mpj8RWSw

###

PUT https://backend-final-project-eight.vercel.app/comments/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjU2Njc4NTcwNX0.GOAhma8VrYcfFAECGqJG-Rv_wNSUOhdu-s6Mpj8RWSw

{
  "postId": 2,
  "userId": 2,
  "comment": "Ini adalah komentar yang sudah diedit dari postId 2 dan userId 2"
}